id: P004297
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17114
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན།
  author: ''
  volumes:
    594e97bd959848a28c5b4d69bc6823e8:
      image_group_id: I1KG17128
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
    f67c5afb3e264d36a770342b811196fb:
      image_group_id: I1KG17129
      title: ''
      volume_number: 2
      total_pages: 356
      base_file: v002.txt
