id: I30540B2F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:36:22+00:00'
last_modified: '2022-06-07T21:47:01.420666+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17114
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FA41:
      image_group_id: I1KG17128
      title: ''
      total_pages: 540
      order: 1
      base_file: FA41.txt
    D4B4:
      image_group_id: I1KG17129
      title: ''
      total_pages: 356
      order: 2
      base_file: D4B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
