id: I30540B2F
legacy_id: P004297
ocr_import_info:
  bdrc_scan_id: W1KG17114
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T23:33:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:24:42.881337+00:00'
last_modified: 2022-08-27 14:26:03.699591
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17114
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17114
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན།
  author: འཇམ་དབྱངས་བཞད་པ ༠༡་ངག་དབང་བརྩོན་འགྲུས།
statistics:
  ocr_word_mean_confidence_index: 0.9034016308681654
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG17129:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17129
      total_pages: 356
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG17129.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8987454690970433
    legacy_id: v002
  I1KG17128:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17128
      total_pages: 540
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17128.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9064285074722684
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
